name: Build and test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        node-version: ['18']

    name: ${{ matrix.platform }} / Node.js v${{ matrix.node-version }}
    runs-on: ${{ matrix.platform }}
    steps:
      - run: git config --global core.autocrlf false # Preserve line endings
      - uses: actions/checkout@v3
      - name: Setup Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build packages
        run: npm run build
      - if: matrix.platform == 'ubuntu-latest'
        name: Build Docker images
        run: npm run docker:build
      - name: Lint packages
        run: npm run lint
      - name: Test packages
        run: npm test

  test_all:
    if: always()
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check build matrix status
        if: ${{ needs.test.result != 'success' }}
        run: exit 1
